# Generated by Django 4.2 on 2023-04-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('use', models.CharField(max_length=500)),
            ],
        ),
    ]
